name: pytorch ci

on:
  workflow_dispatch:

env:
  PVC_PATH: '/nvme/share/share/github/cibuild/${{ github.repository }}'
  SOURCE_PATH: '/nvme/share/share/github/sourcecode'
  HOME: "/var/lib/jenkins"
  CI_IMAGE: "registry.sensetime.com/parrots/ci:linux-bionic-cuda11.7-cudnn8-py3-gcc7"
  BUILD_ENVIRONMENT: "linux-bionic-cuda11.7-py3.10-gcc7"
  PYTORCH_COMMIT: "461f088"
  TORCH_CUDA_ARCH_LIST: "Volta;7.0;7.5;8.0;8.6"


jobs:
  Checkout:
    name: pull and rsync
    runs-on: tps-pytorch-ci
    timeout-minutes: 240
    steps:
      - name: rsync repo
        run: |
          cd ${SOURCE_PATH}/pytorch/pytorch && git pull
          cd ${PVC_PATH} && rm -rf ${GITHUB_RUN_NUMBER} && mkdir -p ${GITHUB_RUN_NUMBER}/artifacts
          rsync -a ${SOURCE_PATH}/pytorch/pytorch ${PVC_PATH}/${GITHUB_RUN_NUMBER}/
          cd ${PVC_PATH}/${GITHUB_RUN_NUMBER}
          mv pytorch source && cd source && git checkout ${PYTORCH_COMMIT} && git submodule sync && git submodule update --init --recursive
      - name: ci interruptible and support pr ci
        run: |
          cd ${SOURCE_PATH}/tools && bash ci_interruptible.sh
        env:
          GITHUB_TOKEN: "${{ secrets.CI_TOKEN }}"

  linux-cuda117-py310-gcc7-build:
    name: linux-cuda117-py310-gcc7-build
    runs-on: tps-pytorch-ci
    needs: [Checkout]
    timeout-minutes: 240
    env:
      DEBUG: 0
    steps:
      - name: build
        run: |
          set -e
          set -o pipefail
          cd ${PVC_PATH}/${GITHUB_RUN_NUMBER}/source && echo '${{ toJSON(env) }}' |grep -v '{\|}'> ${GITHUB_JOB} && sed -i 's/\"//g' ${GITHUB_JOB} && sed -i 's/,//g' ${GITHUB_JOB} && sed -i 's/:[ ]/=\"/g' ${GITHUB_JOB} && sed -i 's/$/&\"/' ${GITHUB_JOB} && sed -i 's/^/&export/' ${GITHUB_JOB}
          container_name=$(docker run --tty --detach \
          -v ${PVC_PATH}/${GITHUB_RUN_NUMBER}/:/home/ \
          -v ${SOURCE_PATH}/tools:${HOME}/tools \
          ${CI_IMAGE} )
          docker exec -t "${container_name}" bash -c "source ${HOME}/tools/run.sh && cd /home/source/ && source ${GITHUB_JOB} && bash .ci/pytorch/build.sh && cp -R build dist .pytorch-test-times.json /home/artifacts/ " \
          && docker rm -f ${container_name} || ( docker rm -f ${container_name} && exit 1 )

  linux-cuda117-py310-gcc7-test:
    name: linux-cuda117-py310-gcc7-test
    uses: ./.github/workflows/_linux-test.yml
    needs: [linux-cuda117-py310-gcc7-build]
    with:
      test-matrix: |
        { include: [
        { config: "default", shard: 1, num_shards: 5, gpu_num: 1 },
        { config: "default", shard: 2, num_shards: 5, gpu_num: 1 },
        { config: "default", shard: 3, num_shards: 5, gpu_num: 1 },
        { config: "default", shard: 4, num_shards: 5, gpu_num: 1 },
        { config: "default", shard: 5, num_shards: 5, gpu_num: 1 },
        { config: "distributed", shard: 1, num_shards: 3, gpu_num: 2 },
        { config: "distributed", shard: 2, num_shards: 3, gpu_num: 2 },
        { config: "distributed", shard: 3, num_shards: 3, gpu_num: 2 },
        ]}